modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/mahmudindev/mcmod-beta173dimension"
license = "ARR"

[[mods]]
modId = "beta173dimension"
version = "${version}"
displayName = "Beta 1.7.3 Dimension"
authors = "mahmudindev"
description = '''
Add beta 1.7.3 world generation as separate dimension.
'''
logoFile = "assets/beta173dimension/icon.png"

[[dependencies.beta173dimension]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.beta173dimension]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.beta173dimension]]
modId = "moderner_beta"
type = "required"
versionRange = "[3.1.4,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.beta173dimension]]
modId = "dimensionfixer"
type = "required"
versionRange = "[0.0.9,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.beta173dimension]]
modId = "worldportal"
type = "required"
versionRange = "[0.0.9,)"
ordering = "NONE"
side = "SERVER"

[[mixins]]
config = "beta173dimension.mixins.json"
